repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.7
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Not running the formatter due to `COM812` https://docs.astral.sh/ruff/rules/missing-trailing-comma/.
    # - id: ruff-format