[tool.pytest.ini_options]
addopts    = "-ra -q"  # -ra: show summary for all tests, -q: quiet mode
minversion = "6.0"
testpaths  = ["tests"]
pythonpath = [
  "."
]


[tool.ruff]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

include        = ["*.ipynb", "*.py", "*.pyi"] # ensure to run on all python files
indent-width   = 4                            # black default
line-length    = 88                           # black default
target-version = "py312"

[tool.ruff.format]
docstring-code-format      = true
docstring-code-line-length = "dynamic"
indent-style               = "space"
line-ending                = "auto"
quote-style                = "double"
skip-magic-trailing-comma  = false

[tool.ruff.lint]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
fixable = ["ALL"]
ignore = [
  "D212",
  "D203",
  "D401",
  "D415",
  "ERA001",
  "FBT003",
  "N812",
  "UP007",
  "TD003",
  "FIX002",
  "FBT001",
  "FBT002",
  "UP017",
  "PD901",
  "PTH123"
]
select = ["ALL"]
unfixable = [
    "F401", # unused-import
    "F841", # unused-variable
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["D104"]
"*/__init__.py" = ["F401"]
"*/config.py" = ["N805", "ANN001", "ANN201"]
"tests/*" = [
  "ANN001",
  "ANN201",
  "D100",
  "D101",
  "D102",
  "D103",
  "INP001",
  "S101",
  "PD901",
  "T201",
  "ARG001",
  "PLR2004"
  ]
  "execute.py" = ["T201"]
